const colorObject = require('./get-color-object.js');

/**
 * Generates color objects for each color defined in the palette. It utilizes the colorObject function
 * to process each color individually, creating detailed configurations for tints, shades, and additional
 * color information across various color spaces.
 *
 * @param {Object} palette - The color palette containing configurations for base colors, levels, max limits,
 *                           and optional mixing instructions for each color.
 * @returns {Object} An object where each property corresponds to a color name in the palette, and its value
 *                   is a detailed color object generated by the colorObject function, including tints, shades,
 *                   and color information in multiple color spaces.
 */
module.exports = palette => {
   const allColors = Object.keys(palette);
   const color = {};

   allColors.forEach(colorName => {
      color[colorName] = colorObject(colorName, palette);
   });

   return color;
};
